config/routes.rb
CapacityPlanning::Application.routes.draw do
  resources :workloads

  resources :availabilities

  resources :workers

  resources :projects

  resources :assignments

  
  match ':year/:week(.:format)' => "application#date",
    :constraints => { :year => /\d{4}/, :week => /\d{1,2}/ },
    :as => "date",
    :via => :get,
    :defaults => { :format => 'html' }
  match ':abbr(.:format)' => "application#abbr",
    :constraints => { :abbr => /last|current|next/ },
    :via => :get,
    :defaults => { :format => 'html' }
  match '/' => "application#index",
    :via => :get,
    :defaults => { :format => 'html' }
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  include Week
  belongs_to :worker
  belongs_to :project
  validates_numericality_of :days_per_week, :greater_than_or_equal_to => Week::DAYS_PER_WEEK.min, :less_than_or_equal_to => Week::DAYS_PER_WEEK.max

  def self.get_assignments year, week
    get_worker_project_table do |worker, project|
        assignment = worker.get_assignment project, year, week 
        if assignment.nil?
          assignment = Assignment.new :from_year => year, :from_week => week, :worker => worker, :project => project
        elsif assignment.from_year != year.to_i || assignment.from_week != week.to_i
          assignment = Assignment.new :from_year => year, :from_week => week, :worker => worker, :project => project, :days_per_week => assignment.days_per_week
        end
        [project, assignment]
    end
  end

  def self.get_assignment_days year, week
    get_worker_project_table do |worker, project| 
        assignment = worker.get_assignment project, year, week 
        [project, assignment.present? ? assignment.days_per_week : 0]
    end
  end

  def self.get_worker_project_table
    Hash[Worker.all.map do | worker |
      [worker,
      Hash[Project.all.map do | project |
           yield worker, project
      end]]
    end]
  end

  def update_or_delete attributes
    if  (attributes[:from_year].nil?  || attributes[:from_year].to_i  == self.from_year) &&
        (attributes[:from_week].nil?  || attributes[:from_week].to_i  == self.from_week) &&
        (attributes[:worker_id].nil?  || attributes[:worker_id].to_i  == self.worker_id) &&
        (attributes[:project_id].nil? || attributes[:project_id].to_i == self.project_id) &&
        attributes[:days_per_week].present? && attributes[:days_per_week] != self.days_per_week
      update_or_delete_days_per_week attributes
    else
      update_attributes attributes
    end
  end

  protected

  def update_or_delete_days_per_week attributes
    previous_days_per_week = self.previous_days
    if previous_days_per_week == attributes[:days_per_week].to_i
      self.destroy
    else
      update_attributes attributes
    end
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render json: @assignment, status: :created, location: @assignment }
        format.js 
      else
        format.html { render action: "new" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
        format.js{ render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_or_delete(params[:assignment])
        if @assignment.destroyed?
          format.html { redirect_to Assignment.new, notice: 'Assignment was successfully deleted.' }
          format.json { head :no_content } # json not tested; should it redirect?
          format.js 
        else
          format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
          format.json { head :no_content }
          format.js 
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
        format.js { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :days_per_week %>
  <%= f.select :days_per_week, 1..5 %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/_form_days_only.html.erb
<%= form_for(assignment, :remote => true) do |f| %>
  <%= f.select :days_per_week, Week::DAYS_PER_WEEK, {}, {:class => 'submittable'} %>
  <%= f.hidden_field :from_year %>
  <%= f.hidden_field :from_week %>
  <%= f.hidden_field :worker_id %>
  <%= f.hidden_field :project_id %>
  <%= f.submit :submit, {:class => 'assignment_button'} %>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= link_to 'Show', assignment %></td>
    <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
    <td><%= link_to 'Destroy', assignment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>