config/routes.rb
CapacityPlanning::Application.routes.draw do
  resources :workloads

  resources :availabilities

  resources :workers

  resources :projects

  resources :assignments

  
  match ':year/:week(.:format)' => "application#date",
    :constraints => { :year => /\d{4}/, :week => /\d{1,2}/ },
    :as => "date",
    :via => :get,
    :defaults => { :format => 'html' }
  match ':abbr(.:format)' => "application#abbr",
    :constraints => { :abbr => /last|current|next/ },
    :via => :get,
    :defaults => { :format => 'html' }
  match '/' => "application#index",
    :via => :get,
    :defaults => { :format => 'html' }
end

app/models/workload.rb
class Workload < ActiveRecord::Base
  include Week
  belongs_to :project
  validates_numericality_of :days_per_week, :greater_than_or_equal_to => 0

  def self.get_workloads year, week
    get_projects do |project|
        workload = project.get_workload year, week 
        if workload.nil?
          workload = Workload.new :from_year => year, :from_week => week, :project => project
        elsif workload.from_year != year.to_i || workload.from_week != week.to_i
          workload = Workload.new :from_year => year, :from_week => week, :project => project, :days_per_week => workload.days_per_week
        end
        workload
    end
  end

  def self.get_workload_days year, week
    get_projects do |project| 
        workload = worker.get_workload year, week 
        [project, workload.present? ? workload.days_per_week : 0]
    end
  end

  def self.get_projects
    Hash[Project.all.map do | project |
      [project, yield(project)]
    end]
  end
end

app/controllers/workloads_controller.rb
class WorkloadsController < ApplicationController
  # POST /workloads
  # POST /workloads.json
  def create
    @workload = Workload.new(params[:workload])

    respond_to do |format|
      if @workload.save
        format.html { redirect_to @workload, notice: 'Workload was successfully created.' }
        format.json { render json: @workload, status: :created, location: @workload }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @workload.errors, status: :unprocessable_entity }
        format.js{ render json: @workload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workloads/1
  # PUT /workloads/1.json
  def update
    @workload = Workload.find(params[:id])

    respond_to do |format|
      if @workload.update_or_delete(params[:workload])
        if @workload.destroyed?
          format.html { redirect_to Workload.new, notice: 'Workload was successfully deleted.' }
          format.json { head :no_content } # json not tested; should it redirect?
          format.js 
        else
          format.html { redirect_to @workload, notice: 'Workload was successfully updated.' }
          format.json { head :no_content }
          format.js 
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @workload.errors, status: :unprocessable_entity }
        format.js{ render json: @workload.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/workloads_helper.rb
module WorkloadsHelper
end

app/views/workloads/_form.html.erb
<%= form_for(@workload) do |f| %>
  <% if @workload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workload.errors.count, "error") %> prohibited this workload from being saved:</h2>

      <ul>
      <% @workload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workloads/_form_days_only.html.erb
<%= form_for(workload, :remote => true) do |f| %>
  <%= f.select :days_per_week, 0..(Week::DAYS_PER_WEEK.max * @workers.length), {}, {:class => 'submittable'} %>
  <%= f.hidden_field :from_year %>
  <%= f.hidden_field :from_week %>
  <%= f.hidden_field :project_id %>
  <%= f.submit :submit, {:class => 'workload_button'} %>
<% end %>

app/views/workloads/create.js.erb
<%= render :partial => 'create_or_update' %>

app/views/workloads/edit.html.erb
<h1>Editing workload</h1>

<%= render 'form' %>

<%= link_to 'Show', @workload %> |
<%= link_to 'Back', workloads_path %>

app/views/workloads/index.html.erb
<h1>Listing workloads</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workloads.each do |workload| %>
  <tr>
    <td><%= link_to 'Show', workload %></td>
    <td><%= link_to 'Edit', edit_workload_path(workload) %></td>
    <td><%= link_to 'Destroy', workload, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Workload', new_workload_path %>

app/views/workloads/new.html.erb
<h1>New workload</h1>

<%= render 'form' %>

<%= link_to 'Back', workloads_path %>

app/views/workloads/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_workload_path(@workload) %> |
<%= link_to 'Back', workloads_path %>