config/routes.rb
CapacityPlanning::Application.routes.draw do
  resources :workloads

  resources :availabilities

  resources :workers

  resources :projects

  resources :assignments

  
  match ':year/:week(.:format)' => "application#date",
    :constraints => { :year => /\d{4}/, :week => /\d{1,2}/ },
    :as => "date",
    :via => :get,
    :defaults => { :format => 'html' }
  match ':abbr(.:format)' => "application#abbr",
    :constraints => { :abbr => /last|current|next/ },
    :via => :get,
    :defaults => { :format => 'html' }
  match '/' => "application#index",
    :via => :get,
    :defaults => { :format => 'html' }
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_many :availabilities
  has_many :assignments

  default_scope where(:deleted_from_year => nil)

  def self.deleted
    self.unscoped.where(arel_table[:deleted_from_year].not_eq nil)
  end

  def get_available_days year, week
    availability = get_availability( year, week )
    availability.present? ? availability.days_per_week : 0
  end
  
  def get_availability year, week
    Availability.
      where( :worker_id => self.id ).
      where( "from_year < ? or (from_year = ? AND from_week <= ?)", year, year, week ).
      order( :from_year, :from_week ).
      last
  end
  
  def get_assignment project, year, week
    Assignment.
      where( :worker_id => self.id ).
      where( :project_id => project.id ).
      where( "from_year < ? or (from_year = ? AND from_week <= ?)", year, year, week ).
      order( :from_year, :from_week ).
      last
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workers }
    end
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
    @worker = Worker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @worker }
    end
  end

  # GET /workers/new
  # GET /workers/new.json
  def new
    @worker = Worker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @worker }
    end
  end

  # GET /workers/1/edit
  def edit
    @worker = Worker.find(params[:id])
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(params[:worker])

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render json: @worker, status: :created, location: @worker }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
        format.js { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workers/1
  # PUT /workers/1.json
  def update
    @worker = Worker.find(params[:id])

    respond_to do |format|
      if @worker.update_attributes(params[:worker])
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
        format.js { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker = Worker.find(params[:id])
    @worker.destroy

    respond_to do |format|
      format.html { redirect_to workers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_availability_form.html.erb
<%= form_for(availability, :remote => true) do |f| %>
  <%= f.select :days_per_week, 0..5, {}, {:class => 'submittable'} %>
  <%= f.hidden_field :from_year %>
  <%= f.hidden_field :from_week %>
  <%= f.hidden_field :worker_id %>
  <%= f.submit :submit, {:class => 'availability_button'} %>
<% end %>

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% @worker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/_form_names_only.html.erb
<%= form_for(worker, :remote => true) do |f| %>
  <%= f.text_field :name, {:class => 'submittable'} %>
  <%= f.submit :submit, {:class => 'worker_button'} %>
<% end %>

app/views/workers/create.js.erb
<%#= render :partial => 'create_or_update' %>
window.location.reload()

app/views/workers/edit.html.erb
<h1>Editing worker</h1>

<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<h1>Listing workers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workers.each do |worker| %>
  <tr>
    <td><%= link_to 'Show', worker %></td>
    <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
    <td><%= link_to 'Destroy', worker, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Worker', new_worker_path %>

app/views/workers/new.html.erb
<h1>New worker</h1>

<%= render 'form' %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>

app/views/workers/update.js.erb
<%= render :partial => 'create_or_update' %>